# Generated by Django 2.2 on 2020-02-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='sample_site',
            new_name='portfolio_site',
        ),
    ]
